# Usa una imagen oficial de Node.js
FROM node:20-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia el package.json y package-lock.json (si existe)
COPY package*.json ./

# Instala las dependencias y Angular CLI globalmente
RUN npm install
RUN npm install -g @angular/cli@21

# Nota: El código fuente se montará como volumen (hot-reloading) en el docker-compose.
# COPY . .

# Expone el puerto de Angular
EXPOSE 4200

# Comando para correr Angular con host 0.0.0.0 para que se pueda acceder desde fuera del contenedor
# --poll 2000 permite que Docker en Windows detecte los cambios de archivos correctamente.
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]
