server {
    listen 80;
    server_name erpliceo.ddns.net 54.87.191.204 localhost;

    # Redirigir tráfico HTTP a HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name erpliceo.ddns.net;

    ssl_certificate /etc/letsencrypt/live/erpliceo.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/erpliceo.ddns.net/privkey.pem;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Para que Angular maneje las rutas correctamente
    location / {
        try_files $uri $uri/ /index.html;
    }
}
